name: Download APK Direct

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download APK from official release
        run: |
          wget -O byedpi.apk "https://github.com/dovecoteescapee/ByeDPIAndroid/releases/download/v1.2.0/byedpi-1.2.0.apk"
          
      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: byedpi-apk
          path: byedpi.apk
